Attempt to allow preferunits to work with non-pure units
PainterQubits/Unitful.jl pull request #478
Opened 2021-08-22 04:29 UTC by lukebemish

Should fix #457. Prior to this change, attempts to use something that looked like "preferunits(C/ms)" would result in strange behavior, without throwing any sort of errors. Now, that should work nicely. This means that, for example:

```
julia> Unitful.preferunits(u"ms",u"C/ms")

julia> upreferred(50u"A")
1//20 C ms^-1

julia> upreferred(50u"mA*ns")
1//20000000000 C

julia> upreferred(50u"mA/mC")
1//20 ms^-1
```

preferunits still requires units with pure dimensions of power=1.

I ran all of the tests and looked through the rest of the code for anywhere this could cause issues or incompatibilities, and I couldn't find anything, as upreferred(x::Dimensions) and preferunits seem to be the only things that touch the promotions Dict.

2021-10-05 06:14 UTC, sostock commented on src/user.jl
> +    # so we won't stop them, just let them know they're doing it.
I would like to know what the other maintainers think about printing a warning here. On one hand, if it works correctly, why print a warning? It adds noise and slows down the code. On the other hand, I cannot think of a real usecase for preferred units based on different base units, so it is most likely a mistake and printing a warning is a good solution.

2021-11-06 23:26 UTC, giordano requested changes

2021-11-06 23:26 UTC, giordano commented on src/user.jl
> +    ulist = [([typeof(i[2]).parameters[1] for i in promotion]...)...]
I'm confused by this line:
```julia
[typeof(i[2]).parameters[1] for i in promotion]
```
is a vector generated by comprehension, then you splat it in a tuple, then you splat the tuple in a vector again?

Why not just
```suggestion
    ulist = (typeof(i[2]).parameters[1] for i in promotion)
```
which is a lazy generator instead?

2021-11-06 23:26 UTC, giordano commented on src/user.jl
> +    ulist = [i^(1/i.power) for i in ulist]
Similar to the line above, you can use a lazy generator instead of allocating a vector:
```suggestion
    ulist = (i^(1/i.power) for i in ulist)
```

2021-11-06 23:26 UTC, giordano commented on src/units.jl
> +    u = prod([Unitful.NoUnits, (Unitful.promotion[name(z)]^z.power for z in D)...])
Also here you can avoid allocating an array:
```suggestion
    u = prod((Unitful.NoUnits, (Unitful.promotion[name(z)]^z.power for z in D)...))
```

2021-11-06 23:26 UTC, giordano commented on src/user.jl
> +    check = Dict()
Can this dictionary by typed?

2021-11-06 23:26 UTC, giordano commented on src/user.jl
> +    # so we won't stop them, just let them know they're doing it.
I'm not sure `preferunits` is a performance-critical function, so slowing it down is fine, in my opinion.  I think removing a warning is non-breaking, so we could change the behaviour later in case we don't like it.

2021-11-06 23:26 UTC, giordano commented on test/runtests.jl
> +        @test_logs (:warn,) Unitful.preferunits(C/ms)
I'd check the message with something like
```suggestion
        @test_logs (:warn, r"^Preferred units contain complex units") Unitful.preferunits(C/ms)
```
to make sure we aren't catching something else by accident (even though it's very unlikely)

2021-11-06 23:26 UTC, giordano commented on src/user.jl
> +                @warn "Prefered units contain complex units based on units of the same dimension but different scales: "*string(i)*" and "*string(check[k])*
```suggestion
                @warn "Preferred units contain complex units based on units of the same dimension but different scales: "*string(i)*" and "*string(check[k])*
```

2021-11-09 23:30 UTC, giordano approved these changes
Looks better to me now

2021-11-10 12:02 UTC, sostock commented on src/user.jl
> +            k = string(dimension(i))
I wouldn’t use `string` for this, because it doesn’t have to be unique (it’s possible to define different dimensions that print the same, although I wouldn’t recommend it). The symbol associated with a dimension (like `:Length`) must be unique, it’s better to use that.
We could define a function like
```julia
function pure_dimension(x::Units) = pure_dimension(dimension(x))
function pure_dimension(::Dimensions{D}) where D
    (isone(length(D)) && isone(D[1].power)) || error("dimension is not pure")
    D[1]
end
```
and then use `name(pure_dimension(i))` instead of `string(dimension(i))`. I haven’t tested it though.

2021-11-10 16:42 UTC, lukebemish commented on src/user.jl
> +            k = string(dimension(i))
The reason I went with this is that the dimensions here don't have to be pure - this would also work if the user defined something in terms of, say, `mC` and `C`. I agree that the string representation is sup-par. I also think I figured it out, though; it works just fine if we just use `dimension(i)` as a dictionary key, since as far as I'm aware a `Unitful.Dimensions` object should be hashable.

2021-11-11 07:21 UTC, sostock commented on src/units.jl
> +    u = prod((Unitful.NoUnits, (Unitful.promotion[name(z)]^z.power for z in D)...))
```suggestion
    u = prod((NoUnits, (promotion[name(z)]^z.power for z in D)...))
```
This is part of the `Unitful` module, so these module qualifiers aren’t necessary.

2021-11-11 07:21 UTC, sostock commented on src/user.jl
> +    check = Dict{Unitful.Dimensions, Unit}()
```suggestion
    check = Dict{Dimensions, Unit}()
```

2021-11-11 07:21 UTC, sostock commented on test/runtests.jl
> +        Unitful.preferunits(A)
Note that resetting this will not restore the behavior of `upreferred(u"V/m")`. Because `upreferred(::Dimensions)` is a generated method, it will only restore the original behavior for dimensions on which `upreferred` has not been called yet.

2021-11-11 07:21 UTC, sostock commented on test/runtests.jl
> +        @test dimension(upreferred(u"V/m")) == dimension(u"V/m")
```suggestion
        @test @inferred(upreferred(V/m)) == kg*m*C^-1*s^-2
        @test dimension(upreferred(V/m)) == dimension(V/m)
```
All of these units are imported, so we don’t need the `u"…"` macro.

2021-11-11 17:01 UTC, lukebemish commented on test/runtests.jl
> +        Unitful.preferunits(A)
Good to know. Is this likely to mess with anything elsewhere in the tests, now or in the future, or should we just leave it as is or remove the `Unitful.preferunits(A)`?

2021-11-12 09:26 UTC, sostock commented on test/runtests.jl
> +        Unitful.preferunits(A)
To avoid potential confusion in the future, we could move these tests to the end (i.e., move the testset to the end of the test suite and the new tests to the end of the testset), but I don’t think that’s necessary. Maybe the comment could be extended, e.g.
```
# Reset preferred units to default, except for units of dimension 𝐋*𝐌*𝐈^-1*𝐓^-3,
# because upreferred has already been called for that dimension
```

2021-11-12 09:31 UTC, sostock approved these changes

2021-11-29 23:26 UTC, merged