Fix some major invalidations to improve compile times
PainterQubits/Unitful.jl pull request #509
Opened 2021-12-24 01:01 UTC by ChrisRackauckas

Unitful.jl was flagged as a major invalidator of compilation downstream. Test:

```julia
# From: https://timholy.github.io/SnoopCompile.jl/stable/snoopr/
using SnoopCompile
invalidations = @snoopr begin
    using DifferentialEquations

    function lorenz(du,u,p,t)
     du[1] = 10.0(u[2]-u[1])
     du[2] = u[1]*(28.0-u[3]) - u[2]
     du[3] = u[1]*u[2] - (8/3)*u[3]
    end
    u0 = [1.0;0.0;0.0]
    tspan = (0.0,100.0)
    prob = ODEProblem(lorenz,u0,tspan)
    alg = Rodas5()
    tinf = solve(prob,alg)
end;

trees = SnoopCompile.invalidation_trees(invalidations);

@show length(SnoopCompile.uinvalidated(invalidations)) # show total invalidations

show(trees[end]) # show the most invalidated method
```

This method won the prize for the absolute most invalidations :tada:. But I think the bigger issue is that it simply doesn't follow Julia semantics. It fixes the types for issue https://github.com/PainterQubits/Unitful.jl/issues/127 in a way that gives a stricter type than Julia would do in the normal cases (which is why the invalidation occurs).

After this PR, heterogeneous arrays of numbers with Quantity in there act normally, and compile times are back to normal. Here's a showcase of it being normal:

```julia

using Unitful, Test
m = u"m"
cm = u"cm"

b = Union{Complex,Float64}[0 + 0im, 0.0]
@test b + b == b
@test b .+ b == b
@test eltype(b+b) === Number

b = Number[0 + 0im, 0.0]
@test b + b == b
@test b .+ b == b
@test eltype(b+b) === Number

b = [0.0, 0.0m]
@test b + b == b
@test b .+ b == b
@test eltype(b+b) === Number
```

2021-12-24 01:02 UTC, ChrisRackauckas commented
It would be good if this could get a quick review because it effects a lot of downstream compile times @sostock

2021-12-24 09:38 UTC, giordano requested changes

2021-12-24 09:38 UTC, giordano commented on src/promotion.jl
> +Base.promote_typejoin(::Type{Quantity{S,D,U}}, ::Type{Quantity{T,D,U}}) where {T,S,D,U} = Quantity{T,S}
I don't think `Quantity{T,S}` is correct: the second parameter should be the dimension, not another numeric type.  However, tests as you modified them pass for me without this method at all

2021-12-24 09:54 UTC, giordano commented
I'd argue it's a bit weird that in
```julia
julia> b = [0.0, 0.0u"m"]
2-element Vector{Quantity{Float64}}:
   0.0
 0.0 m

julia> b + b
2-element Vector{Number}:
     0.0
 0.0 m
```
`b` and `b + b` have different eltypes (I think that the proper eltype in both cases should be `Number`), but this is probably outside of the scope of this PR.

2021-12-24 10:05 UTC, ChrisRackauckas commented on src/promotion.jl
> +Base.promote_typejoin(::Type{Quantity{S,D,U}}, ::Type{Quantity{T,D,U}}) where {T,S,D,U} = Quantity{T,S}
Yeah, the better thing might be to completely remove this overload.

2021-12-27 08:05 UTC, sostock approved these changes

2021-12-27 11:18 UTC, giordano approved these changes

2021-12-27 11:19 UTC, merged