Fix printing of StepRangeLen with affine units
PainterQubits/Unitful.jl pull request #551
Opened 2022-08-30 01:52 UTC by tomyun

This fixed a printing issue (#550) with `range` structures (`StepRange`, `StepRangeLen`) defined with `°C` as a primary unit and `K` as a step unit.

Before:
```
julia> StepRange(1u"°C", 1u"K", 3u"°C")
(1//1:-5443//20:3//1) °C

julia> StepRange(1u"°C", 1.0u"K", 3u"°C")
(1.0:-272.15:273.15) °C

julia> StepRangeLen{typeof(1u"°C"),typeof(1u"°C"),typeof(1u"K")}(1u"°C", 1u"K", 3, 1)
(1//1:-5443//20:-5433//10) °C

julia> StepRangeLen{typeof(1.0u"°C"),typeof(1.0u"°C"),typeof(1u"K")}(1.0u"°C", 1u"K", 3, 1)
(1.0:-272.15:-543.3) °C
```

After:
```
julia> StepRange(1u"°C", 1u"K", 3u"°C")
(1:1:3) °C

julia> StepRange(1u"°C", 1.0u"K", 3u"°C")
(1.0:1.0:3.0) °C

julia> StepRangeLen{typeof(1u"°C"),typeof(1u"°C"),typeof(1u"K")}(1u"°C", 1u"K", 3, 1)
(1:1:3) °C

julia> StepRangeLen{typeof(1.0u"°C"),typeof(1.0u"°C"),typeof(1u"K")}(1.0u"°C", 1u"K", 3, 1)
(1.0:1.0:3.0) °C
```

2022-09-02 06:48 UTC, sostock requested changes
This will lead to wrong printing for ranges whose `eltype` and `step` have different units.

Before this PR (correct):
```julia
julia> StepRange((1//1)u"m", 1u"cm", (2//1)u"m")
(1//1:1//100:2//1) m
```
After this PR (incorrect):
```julia
julia> StepRange((1//1)u"m", 1u"cm", (2//1)u"m")
(1//1:1:2//1) m
```

The suggestions below show how I would fix this.

2022-09-02 06:48 UTC, sostock commented on src/display.jl
> +    V = unit(s)
```suggestion
```

2022-09-02 06:48 UTC, sostock commented on src/display.jl
> +        show(io, ustrip(U, a):ustrip(V, s):ustrip(U, b))
```suggestion
        show(io, ustrip(U, a):ustrip(absoluteunit(U), s):ustrip(U, b))
```

2022-09-02 06:48 UTC, sostock commented on src/display.jl
> +    V = unit(s)
```suggestion
```

2022-09-02 06:48 UTC, sostock commented on src/display.jl
> +    show(io, StepRangeLen(ustrip(U, a), ustrip(V, s), length(r)))
```suggestion
    show(io, StepRangeLen(ustrip(U, a), ustrip(absoluteunit(U), s), length(r)))
```

2022-09-02 06:48 UTC, sostock commented on test/runtests.jl
> +
```suggestion
        @test repr(StepRange((1//1)u"m", 1u"cm", (2//1)u"m")) == "(1//1:1//100:2//1) m"
        @test repr(StepRangeLen(1.0u"m", 1.0u"cm", 101)) == "(1.0:0.01:2.0) m"

```
Add some tests for ranges where `unit(eltype(r)) != unit(step(r))`

2022-09-02 06:48 UTC, sostock commented on test/runtests.jl
> +        @test repr(StepRange(1u"°C", 1u"K", 3u"°C")) == "(1:1:3) °C"
We could also think about printing this as `(1:3) °C` instead of `(1:1:3) °C` (we do so for non-affine quantities). For this, it should be sufficient to change `U` to `absoluteunit(U)` in line 139 of src/display.jl

2022-09-02 07:16 UTC, sostock requested changes
It would be good to test that it also works correctly when `unit(step(r)) != absoluteunit(unit(eltype(r)))`.

2022-09-02 07:16 UTC, sostock commented on test/runtests.jl
> +        @test repr(StepRange(1u"°C", 1.0u"K", 3u"°C")) == "(1.0:1.0:3.0) °C"
```suggestion
        @test repr(StepRange(1u"°C", 1.0u"K", 3u"°C")) == "(1.0:1.0:3.0) °C"
        @test repr(StepRange((0//1)u"°F", 1u"K", (9//1)u"°F")) == "(0//1:9//5:9//1) °F"
```

2022-09-02 07:16 UTC, sostock commented on test/runtests.jl
> +        @test repr(StepRangeLen{typeof(1.0u"°C"),typeof(1.0u"°C"),typeof(1u"K")}(1.0u"°C", 1u"K", 3, 1)) == "(1.0:1.0:3.0) °C"
```suggestion
        @test repr(StepRangeLen{typeof(1.0u"°C"),typeof(1.0u"°C"),typeof(1u"K")}(1.0u"°C", 1u"K", 3, 1)) == "(1.0:1.0:3.0) °C"
        @test repr(StepRangeLen{typeof(1.0u"°F"),typeof(1.0u"°F"),typeof(1u"K")}(0.0u"°F", 1u"K", 6)) == "(0.0:1.8:9.0) °F"
```

2022-09-03 01:48 UTC, tomyun commented on test/runtests.jl
> +        @test repr(StepRange(1u"°C", 1u"K", 3u"°C")) == "(1:1:3) °C"
That's now incorporated.

2022-09-03 01:49 UTC, tomyun commented
Thanks for suggestions! Just pushed new commits reflecting the changes.

2022-09-03 16:41 UTC, sostock commented
We could either fix the implementation on Julia 1.0 (not sure how difficult it would be, I haven’t looked into it) or simply remove support for Julia <1.6, since that is the current LTS (I checked that the tests pass on Julia 1.6).

@giordano What do you think about removing support for Julia <1.6?

2022-09-03 16:46 UTC, giordano commented
> @giordano What do you think about removing support for Julia <1.6?

That's fine with me.  I generally take a practical approach of supporting old versions until it becomes too much work (unless I have good reasons for keeping compatibility).  Also, v1.6 has been the LTS for a while now.

2022-09-07 08:42 UTC, sostock reviewed
After thinking about it some more, I don’t think we should remove support for Julia 1.0 just for this PR. This PR does not introduce new bugs on Julia 1.0, the added tests just reveal bugs that existed before. This PR only fixes a printing bug. I would just change the offending tests to use `@test_broken` on older Julia versions.

2022-09-07 08:42 UTC, sostock commented on test/runtests.jl
> +        @test repr(StepRangeLen{typeof(1u"°C"),typeof(1u"°C"),typeof(1u"K")}(1u"°C", 1u"K", 3, 1)) == "(1:1:3) °C"
```suggestion
        @static if VERSION < v"1.5"
            @test_broken repr(StepRangeLen{typeof(1u"°C"),typeof(1u"°C"),typeof(1u"K")}(1u"°C", 1u"K", 3, 1)) == "(1:1:3) °C"
        else
            @test repr(StepRangeLen{typeof(1u"°C"),typeof(1u"°C"),typeof(1u"K")}(1u"°C", 1u"K", 3, 1)) == "(1:1:3) °C"
        end
```

2022-09-07 08:42 UTC, sostock commented on test/runtests.jl
> +        @test repr(StepRangeLen{typeof(1.0u"°F"),typeof(1.0u"°F"),typeof(1u"K")}(0.0u"°F", 1u"K", 6)) == "(0.0:1.8:9.0) °F"
```suggestion
        @static if VERSION < v"1.5"
            @test_broken repr(StepRangeLen{typeof(1.0u"°F"),typeof(1.0u"°F"),typeof(1u"K")}(0.0u"°F", 1u"K", 6)) == "(0.0:1.8:9.0) °F"
        else
            @test repr(StepRangeLen{typeof(1.0u"°F"),typeof(1.0u"°F"),typeof(1u"K")}(0.0u"°F", 1u"K", 6)) == "(0.0:1.8:9.0) °F"
        end
```

2022-09-08 07:23 UTC, sostock approved these changes

2022-09-13 06:02 UTC, merged

2022-09-13 06:02 UTC, sostock commented
@tomyun Thanks for the contribution! This will be in Unitful 1.12.