Update `Types` documentation
PainterQubits/Unitful.jl pull request #591
Opened 2022-11-25 19:26 UTC by cmichelenstrofer

Fixes #590

2022-11-28 12:34 UTC, sostock commented
There are still some places where the last type parameter is missing in conversion.md:
https://github.com/PainterQubits/Unitful.jl/blob/7dc9dd7cc3e88706ffa1ee14d9c660164d90a3b3/docs/src/conversion.md?plain=1#L192-L193
https://github.com/PainterQubits/Unitful.jl/blob/7dc9dd7cc3e88706ffa1ee14d9c660164d90a3b3/docs/src/conversion.md?plain=1#L248

2022-11-28 16:58 UTC, sostock commented
I looked through the manual, the three occurrences I pointed out should be the only remaining ones.

2022-11-28 20:59 UTC, cmichelenstrofer commented
Cool. I fixed those three lines. Thanks!

2022-11-29 07:29 UTC, sostock requested changes

2022-11-29 07:29 UTC, sostock commented on docs/src/conversion.md
> +this type signature should be some type `Unitful.FreeUnits{M,D,A}` (the dimensions must be the
```suggestion
this type signature should be some type `Unitful.FreeUnits{M,D,B}` (the dimensions must be the
```
The last parameter does not have to match, so I would change `A` to `B` to reflect that (just like `M` was used instead of `N`).

We could also write something like `Unitful.FreeUnits{N2,D,A2}`, but I’m not sure whether that’s better or worse for understanding.

2022-11-29 15:49 UTC, cmichelenstrofer commented on docs/src/conversion.md
> +this type signature should be some type `Unitful.FreeUnits{M,D,A}` (the dimensions must be the
Ah! Makes sense 👍🏾

2022-11-29 19:48 UTC, sostock approved these changes

2022-11-30 06:48 UTC, merged