support InverseFunctions
PainterQubits/Unitful.jl pull request #622
Opened 2023-02-25 20:39 UTC by aplavin

Useful in, for example:
```julia
using Accessors

x = (a=1, b=1.23m)
y = @set x.b |> ustrip(m, _) = 2.34
# y == (a=1, b=2.34m)

using FlexiMaps

lr = maprange(@optic(log(ustrip(m, _))), 10cm, 10m, length=5)
# lr ≈ [0.1, √0.1, 1, √10, 10]m
```

Only works on 1.9+, no changes on earlier julias.

2023-02-27 11:40 UTC, sostock requested changes

2023-02-27 11:40 UTC, sostock commented on test/runtests.jl
> +    InverseFunctions.test_inverse(Base.Fix1(ustrip, u"m"), 2u"mm")
```suggestion
    InverseFunctions.test_inverse(Base.Fix1(ustrip, m), 2m)
    InverseFunctions.test_inverse(Base.Fix1(ustrip, m), 2mm)
```
The units `m` and `mm` are imported in the test suite, so this can be simplified.

2023-05-09 18:44 UTC, sostock commented
> Test failure seems to be an `Aqua.jl` bug: actually running `]resolve` doesn't change `Project.toml` content.

This is https://github.com/JuliaTesting/Aqua.jl/issues/105. It looks like Aqua wants the sections ordered alphabetically and the entries within the sections ordered alphabetically as well, which is not the order that Pkg uses.

2023-05-09 18:50 UTC, sostock commented on ext/InverseFunctionsUnitfulExt.jl
> +inverse(f::Base.Fix1{typeof(ustrip)}) = Base.Fix1(*, true*f.x)
```suggestion
inverse(f::Base.Fix1{typeof(ustrip), <:Unitful.Units}) = Base.Fix1(*, true*f.x)
```
I would restrict the type of the first `ustrip` argument, because there is currently a discussion about adding another two-argument `ustrip` method where the first argument isn’t a unit (`ustrip(reinterpret, x)`, cf. https://github.com/PainterQubits/Unitful.jl/issues/630#issuecomment-1482765400)

2023-05-10 05:10 UTC, sostock approved these changes

2023-05-11 08:59 UTC, merged

2023-05-11 14:42 UTC, oschulz commented
Regarding the limitation to v1.9 - why not making InverseFunctions a required depencency on <=v1.8? InverseFunctions is extremely lightweight - even on v1.9, using an extension probably won't save even half a millisecond of load time.

2023-05-26 20:22 UTC, oschulz commented
See #652